### ISSUE TITLE
请问一下PrivateKey 这两个怎么赋值

### ISSUE THREAD

**Issue by emisty** [guidao/gopay#4]
PrivateKey *rsa.PrivateKey
PublicKey  *rsa.PublicKey
初始化怎么赋值这两个 525695314希望可以及时回复我

**Comment by jzhbiao** [comment]
PrivateKey *rsa.PrivateKey
PublicKey  *rsa.PublicKey

**Comment by guidao** [comment]
如果你的私钥公钥是pem格式，可以使用encoding/pem包读取数据。再使用  
crypto/x509的下面两个方法解析出公钥跟私钥
x509.ParsePKIXPublicKey(derBytes []byte)
 x509.ParsePKCS8PrivateKey(der []byte)

**Comment by xzghua** [comment]
@guidao  如果不是pem格式的,是通过支付宝那个RSA签名验签工具生成的呢?该如何操作! 
感谢回答!

**Comment by guidao** [comment]
@Yela528  这个看后缀是啥。。。pkcs12可以用包golang.org/x/crypto/pkcs12.

**Comment by xzghua** [comment]
@guidao  我是根据文档 https://docs.open.alipay.com/291/105971/  生成的私钥和公钥,复制出来就是个字符串,操作流程是根据文档 https://docs.open.alipay.com/204/105297/ 进行的!(第一次测试支付开发)

**Comment by guidao** [comment]
@Yela528  可以用crypto/x509的 x509.ParsePKCS1PublicKey跟x509.ParsePKCS1PrivateKey方法。
ps: 支护宝的文档写了是pkcs1格式的。生成的base64字符串，需要先使用base64解码。

**Comment by xzghua** [comment]
已解决,在初始化的时候,先 将 支付宝**RSA签名验签工具** 生成的私钥放在服务器端,格式是 PKCS1  长度是2048   然后,先进行base64进行解密,在 直接利用 x509.ParsePKCS1PrivateKey  ,就可以赋值了,再次感谢 作者的细心回答,十分感谢

**Comment by emisty** [comment]
// 私钥
	block, _ := pem.Decode([]byte(`-----BEGIN PRIVATE KEY-----
xxxxxxxxxxxxxxxxxxxxxxx很长的
-----END PRIVATE KEY-----`))

	if block == nil {
		panic("Sign private key decode error")
	}

	privateKey, err := x509.ParsePKCS8PrivateKey(block.Bytes)
	if err != nil {
		panic(err)
	}

	// 公钥
	block, _ = pem.Decode([]byte(`-----BEGIN PUBLIC KEY-----
		xxxxxxxxxxxxxxxxxxxxxx
-----END PUBLIC KEY-----`))

	if block == nil {
		panic("Sign public key decode error")
	}

	publicKey, err := x509.ParsePKIXPublicKey(block.Bytes)
	if err != nil {
		panic(err)
	}

**Comment by emisty** [comment]
谢谢@guidao

**Comment by guidao** [comment]
@jzhbiao @Yela528 😄。不客气。
